Implement interface of various inventories
stackotter/delta-client pull request #196
Opened 2024-05-28 18:18 UTC by FloofyPlasma

# Description

Implements the interface of various inventories. It doesn't give them full functionality. **Please do not merge until TODO is complete!**

### TODO:
- [ ] Generic_9x1
- [ ] Generic_9x2
- [ ] Generic_9x4
- [ ] Generic_9x5
- [x] Generic_9x6 (Large chests)
- [ ] Generic_3x3 (Dispenser & Dropper)
- [ ] Anvil
- [ ] Beacon
- [ ] Blast Furnace
- [ ] Brewing Stand
- [ ] Enchantment Table (Needs some type of currently unhandled packet, 0x15 otherwise crashes.)
- [ ] Furnace
- [ ] Grindstone
- [ ] Hopper
- [ ] Lectern
- [ ] Loom
- [ ] Merchant (Villager & Wandering trader)
- [ ] Shulker box
- [ ] Smithing table
- [ ] Smoker
- [ ] Cartography table
- [ ] Stonecutter

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

2024-05-29 00:08 UTC, stackotter requested changes
Just left a few quick comments so that you can address them while you're working instead of having to go through a few cycles once the PR's done 😅 just formatting and naming stuff, some of which you already mentioned

2024-05-29 00:08 UTC, stackotter commented on Sources/Core/Sources/GUI/WindowType.swift
> +        },
Remove the extra indent on lines 128-130

2024-05-29 00:08 UTC, stackotter commented on Sources/Core/Sources/GUI/GUISprite.swift
>    case generic9x5
Add `TopHalf` to the end to make it clear that it's not the whole thing

2024-05-29 00:08 UTC, stackotter commented on Sources/Core/Sources/GUI/GUISprite.swift
>    case doubleChest // No top/bottom half since it just uses the full image
Feel free to rename these with their generic names instead. (also don't need the comment once the comment below is resolved cause it'll be clear which have halves and which don't).

2024-05-31 07:26 UTC, FloofyPlasma commented
https://github.com/stackotter/delta-client/pull/196/commits/04b05a6dbe8f280194bb5dbea6f391b466bd1d0f implements dropper and dispenser, not beacon. I'm too tired, oops 😅

2024-06-05 09:25 UTC, stackotter approved these changes
Lgtm 🎉

2024-06-05 09:39 UTC, merged