Issue 8
stackotter/delta-client pull request #60
Opened 2021-11-20 22:32 UTC by Matthew15625

# Description

Fixes #8
- Added picker to select unstable branch

There's a slight problem with it. When you select a branch from the picker it greys out as if it is disabled, even though it isn't. It looks like this is just a SwiftUI bug but I will keep my eye out for any solutions.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

2021-11-20 22:40 UTC, stackotter commented on Sources/Client/Util/Updater.swift
> +      return try Self.getLatestStableDownloadURL()
indent this line one level

2021-11-20 22:42 UTC, stackotter commented on Sources/Client/Util/Updater.swift
> +  /// Geta a list of all workflow runs
typo

2021-11-20 22:43 UTC, stackotter commented on Sources/Client/Views/Config/BranchButton.swift
> +
Remove this new line

2021-11-20 22:49 UTC, stackotter requested changes
Just a few formatting things to change. But the code quality is really good! Nice work 👍

2021-11-20 23:20 UTC, stackotter approved these changes

2021-11-28 09:47 UTC, stackotter approved these changes
Thanks for improving the error handling too :) that's always appreciated

2021-12-26 14:23 UTC, Matthew15625 commented
Wasn't working for some reason so I've tried again at #65 (I'm sure it works this time)

2021-12-26 14:23 UTC, closed without merging